name: coinlib
description:
  A straight-forward, modular library for Peercoin and other Satoshi-based UTXO
  blockchains
version: 4.1.0
repository: https://github.com/peercoin/coinlib

environment:
  sdk: '>=3.2.0 <4.0.0'

dev_dependencies:
  ffigen: ^12.0.0
  lints: ^4.0.0
  test: ^1.21.0

dependencies:
  collection: ^1.17.1
  crypto: ^3.0.2
  dart_base_x: ^1.0.0
  ffi: ^2.1.0
  hex: ^0.2.0
  path: ^1.8.0
  pointycastle: ^3.7.3
  wasm_interop: ^2.0.1

ffigen:
  name: NativeSecp256k1
  description: Raw generated bindings to secp256k1
  output: 'lib/src/secp256k1/secp256k1.ffi.g.dart'
  headers:
    entry-points:
      - 'include/secp256k1_recovery.h'
      - 'include/secp256k1_schnorrsig.h'
      - 'include/secp256k1_ecdh.h'
