analyzer:
  exclude:
    - build/**
    - android/**
    - windows/**
    - linux/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - empty_container_bodies
    - initialize_in_field_declaration
    - unnecessary_const_in_enum_constructor
    - unnecessary_primary_constructor_body
    - unnecessary_type_name_in_constructor
    - use_declaring_parameters

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
