// Relative import to be able to reuse the C sources.
#include "../build/secp256k1-coinlib/src/secp256k1.c"
#include "../build/secp256k1-coinlib/src/precompute_ecmult_gen.c"
#include "../build/secp256k1-coinlib/src/precomputed_ecmult_gen.c"
#include "../build/secp256k1-coinlib/src/precomputed_ecmult.c"
#include "../build/secp256k1-coinlib/src/modules/extrakeys/main_impl.h"
#include "../build/secp256k1-coinlib/src/modules/schnorrsig/main_impl.h"
#include "../build/secp256k1-coinlib/src/modules/ecdh/main_impl.h"
#include "../build/secp256k1-coinlib/src/modules/recovery/main_impl.h"
#include "../build/secp256k1-coinlib/src/modules/musig/main_impl.h"
