// Copyright (c) 2013 Pieter Wuille
//
// Generated from libsecp256k1 headers distributed under the MIT license.
// Source: https://github.com/peercoin/secp256k1-coinlib/tree/69018e5b939d8d540ca6b237945100f4ecb5681e

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// Mapping from Dart function name to native symbol name.
const recordUseMapping = {
  'secp256k1_context_clone': 'secp256k1_context_clone',
  'secp256k1_context_create': 'secp256k1_context_create',
  'secp256k1_context_destroy': 'secp256k1_context_destroy',
  'secp256k1_context_randomize': 'secp256k1_context_randomize',
  'secp256k1_context_set_error_callback':
      'secp256k1_context_set_error_callback',
  'secp256k1_context_set_illegal_callback':
      'secp256k1_context_set_illegal_callback',
  'secp256k1_ec_pubkey_cmp': 'secp256k1_ec_pubkey_cmp',
  'secp256k1_ec_pubkey_combine': 'secp256k1_ec_pubkey_combine',
  'secp256k1_ec_pubkey_create': 'secp256k1_ec_pubkey_create',
  'secp256k1_ec_pubkey_negate': 'secp256k1_ec_pubkey_negate',
  'secp256k1_ec_pubkey_parse': 'secp256k1_ec_pubkey_parse',
  'secp256k1_ec_pubkey_serialize': 'secp256k1_ec_pubkey_serialize',
  'secp256k1_ec_pubkey_sort': 'secp256k1_ec_pubkey_sort',
  'secp256k1_ec_pubkey_tweak_add': 'secp256k1_ec_pubkey_tweak_add',
  'secp256k1_ec_pubkey_tweak_mul': 'secp256k1_ec_pubkey_tweak_mul',
  'secp256k1_ec_seckey_negate': 'secp256k1_ec_seckey_negate',
  'secp256k1_ec_seckey_tweak_add': 'secp256k1_ec_seckey_tweak_add',
  'secp256k1_ec_seckey_tweak_mul': 'secp256k1_ec_seckey_tweak_mul',
  'secp256k1_ec_seckey_verify': 'secp256k1_ec_seckey_verify',
  'secp256k1_ecdh': 'secp256k1_ecdh',
  'secp256k1_ecdsa_recover': 'secp256k1_ecdsa_recover',
  'secp256k1_ecdsa_recoverable_signature_convert':
      'secp256k1_ecdsa_recoverable_signature_convert',
  'secp256k1_ecdsa_recoverable_signature_parse_compact':
      'secp256k1_ecdsa_recoverable_signature_parse_compact',
  'secp256k1_ecdsa_recoverable_signature_serialize_compact':
      'secp256k1_ecdsa_recoverable_signature_serialize_compact',
  'secp256k1_ecdsa_sign': 'secp256k1_ecdsa_sign',
  'secp256k1_ecdsa_sign_recoverable': 'secp256k1_ecdsa_sign_recoverable',
  'secp256k1_ecdsa_signature_normalize': 'secp256k1_ecdsa_signature_normalize',
  'secp256k1_ecdsa_signature_parse_compact':
      'secp256k1_ecdsa_signature_parse_compact',
  'secp256k1_ecdsa_signature_parse_der': 'secp256k1_ecdsa_signature_parse_der',
  'secp256k1_ecdsa_signature_serialize_compact':
      'secp256k1_ecdsa_signature_serialize_compact',
  'secp256k1_ecdsa_signature_serialize_der':
      'secp256k1_ecdsa_signature_serialize_der',
  'secp256k1_ecdsa_verify': 'secp256k1_ecdsa_verify',
  'secp256k1_keypair_create': 'secp256k1_keypair_create',
  'secp256k1_keypair_pub': 'secp256k1_keypair_pub',
  'secp256k1_keypair_sec': 'secp256k1_keypair_sec',
  'secp256k1_keypair_xonly_pub': 'secp256k1_keypair_xonly_pub',
  'secp256k1_keypair_xonly_tweak_add': 'secp256k1_keypair_xonly_tweak_add',
  'secp256k1_musig_adapt': 'secp256k1_musig_adapt',
  'secp256k1_musig_aggnonce_parse': 'secp256k1_musig_aggnonce_parse',
  'secp256k1_musig_aggnonce_serialize': 'secp256k1_musig_aggnonce_serialize',
  'secp256k1_musig_extract_adaptor': 'secp256k1_musig_extract_adaptor',
  'secp256k1_musig_nonce_agg': 'secp256k1_musig_nonce_agg',
  'secp256k1_musig_nonce_gen': 'secp256k1_musig_nonce_gen',
  'secp256k1_musig_nonce_gen_counter': 'secp256k1_musig_nonce_gen_counter',
  'secp256k1_musig_nonce_parity': 'secp256k1_musig_nonce_parity',
  'secp256k1_musig_nonce_process': 'secp256k1_musig_nonce_process',
  'secp256k1_musig_partial_sig_agg': 'secp256k1_musig_partial_sig_agg',
  'secp256k1_musig_partial_sig_parse': 'secp256k1_musig_partial_sig_parse',
  'secp256k1_musig_partial_sig_serialize':
      'secp256k1_musig_partial_sig_serialize',
  'secp256k1_musig_partial_sig_verify': 'secp256k1_musig_partial_sig_verify',
  'secp256k1_musig_partial_sign': 'secp256k1_musig_partial_sign',
  'secp256k1_musig_pubkey_agg': 'secp256k1_musig_pubkey_agg',
  'secp256k1_musig_pubkey_ec_tweak_add': 'secp256k1_musig_pubkey_ec_tweak_add',
  'secp256k1_musig_pubkey_get': 'secp256k1_musig_pubkey_get',
  'secp256k1_musig_pubkey_xonly_tweak_add':
      'secp256k1_musig_pubkey_xonly_tweak_add',
  'secp256k1_musig_pubnonce_parse': 'secp256k1_musig_pubnonce_parse',
  'secp256k1_musig_pubnonce_serialize': 'secp256k1_musig_pubnonce_serialize',
  'secp256k1_schnorrsig_sign': 'secp256k1_schnorrsig_sign',
  'secp256k1_schnorrsig_sign32': 'secp256k1_schnorrsig_sign32',
  'secp256k1_schnorrsig_sign_custom': 'secp256k1_schnorrsig_sign_custom',
  'secp256k1_schnorrsig_verify': 'secp256k1_schnorrsig_verify',
  'secp256k1_selftest': 'secp256k1_selftest',
  'secp256k1_tagged_sha256': 'secp256k1_tagged_sha256',
  'secp256k1_xonly_pubkey_cmp': 'secp256k1_xonly_pubkey_cmp',
  'secp256k1_xonly_pubkey_from_pubkey': 'secp256k1_xonly_pubkey_from_pubkey',
  'secp256k1_xonly_pubkey_parse': 'secp256k1_xonly_pubkey_parse',
  'secp256k1_xonly_pubkey_serialize': 'secp256k1_xonly_pubkey_serialize',
  'secp256k1_xonly_pubkey_tweak_add': 'secp256k1_xonly_pubkey_tweak_add',
  'secp256k1_xonly_pubkey_tweak_add_check':
      'secp256k1_xonly_pubkey_tweak_add_check',
};
